---

- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: True
  tags:
    - 'always'
  tasks: []

- name: install es
  hosts: es-nodes
  roles:
    - ansible-role-elasticsearch
